CREATE DATABASE GREENHOUSE;
USE GREENHOUSE;

CREATE TABLE PLANTS(
	PLANT_NAME CHAR(30) NOT NULL,
   SENSOR_VALUE FLOAT DEFAULT NULL,
   SENSOR_EVENT TIMESTAMP NOT NULL
   DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY PK_PLANTS (PLANT_NAME)
);

SELECT * FROM PLANTS;

SELECT PLANT_NAME, SENSOR_VALUE, SENSOR_EVENT FROM PLANTS;

INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE) VALUES ('Rosa', 0.2319);


INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE) 
VALUES 
	('Cactus', 0.2411),
	('Girassol', 0.3112),
	('Orquídea', 0.4102),
	('Lírio', 0.5566);
	
	
SELECT * FROM plants WHERE PLANT_NAME = 'Cactus';




-- AULA 26/02 --


CREATE DATABASE banco;
USE banco;


CREATE TABLE cliente(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL
);

CREATE TABLE conta(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	numero_conta VARCHAR(10) NOT NULL,
	id_cliente int NOT NULL,
	CONSTRAINT Fk_id_cliente_conta FOREIGN KEY (id_cliente) REFERENCES cliente(id)
);


CREATE TABLE transacao(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_conta INT NOT NULL,
	tipo_transacao INT NOT NULL,
	data_hora DATETIME NOT NULL,
	valor FLOAT NOT NULL,
	FOREIGN KEY (id_conta) REFERENCES conta(id)
);	
	
CREATE INDEX idx_transacao_tp_transacao ON transacao (tipo_transacao);
CREATE INDEX idx_transacap_data_hora ON transacao (data_hora);



